### ISSUE TITLE
  How do I get the Landmarks region on ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3551]
<p>&nbsp;&nbsp;How do I get the Landmarks region on the genome browser to display actual gene names of the browser, rather than just saying "Landmark I: #####" ? </p><p>What were you doing? <br />&nbsp;&nbsp;Looking at the genome browser along with some hits of sequencing results, and trying to equate its position to phenotypic marker genes.</p>

Reported by: John******** (jlb7***************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by chris-grove** [comment]
Duplicate #3550

**Comment by sibyl229** [comment]
Hi John,

Sorry about the problem! Our genome browser expert is looking into it, and will contact you ASAP when it’s fixed. 

Thanks for letting us know.

Sibyl

**Comment by tuli** [comment]
Hi @sibyl229 

Are you able to give me an update on the progress of this ticket? A different user has also noticed the problem. 

Thank you.

**Comment by sibyl229** [comment]
Hi @tuli I think @scottcain is working on this issue. I'm not familiar with the GBrowse codebase. I tried panning through the GBrowse window, and haven't seen any '####'. But I'm not exactly sure where the user saw it.

**Comment by sibyl229** [comment]
Hi @tuli if this landmark label issue is a duplicate of #3550. @scottcain has resolved that one. And the fix has been included in WS247 web app release.

**Comment by tuli** [comment]
Thanks @sibyl229 

@scottcain I have looked on the production and staging site but see that hovering over landmark genes (which is pretty tricky in itself) only pops up the c/some coordinates, not the gene name as it used to.

**Comment by scottcain** [comment]
Weird, this was fixed.  I'm looking at it now.

**Comment by scottcain** [comment]
Fixed on staging and a fix committed.  I can fix this on production too if need be, otherwise it will go out with 248.

**Comment by tuli** [comment]
@scottcain 
It looks fixed to me on Staging, thank you, but the user (Mark Edgley edgley@mail.ubc.ca) still does not see it. He was looking on Staging and tried various browsers. 

Would you mind communicating directly with Mark to see why he can't see the fix.

Thanks.

**Comment by scottcain** [comment]
I suspect it's a caching issue but I'll send him an email to see if we can sort it out.

**Comment by scottcain** [comment]
Fixed with https://github.com/WormBase/website/pull/3792 and the user is happy too!

**Comment by tuli** [comment]
Thanks. We like happy users.
