### ISSUE TITLE
visitor_name (visitor_email): Hello Chris: Hi visi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4655]
_Help Desk chat transcript. Issue can be closed if question was resolved in chat._

visitor_name (visitor_email): Hello</br>Chris: Hi visitor_name, how can I help?</br>visitor_name (visitor_email): Hello Chris, I was looking for the genetic interaction file on the FTP server for WS251, I could not find it. Have you changed the schema for the directory ?</br>Chris: Hmmm, let me take a look</br>visitor_name (visitor_email): OK</br>Chris: I think the file is here:</br>Chris: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/gene_interactions/</br>Chris: but it is currently labeled as "current" instead of "WS251" because that is the current release</br>Chris: it should become archived as "WS251" when WS252 goes live which should be in the next week</br>visitor_name (visitor_email): Ohhhh, I am very sorry</br>Chris: no problem at all</br>visitor_name (visitor_email): Thanks a lot</br>Chris: you're welcome</br>Chris: anything else I can help with?</br>visitor_name (visitor_email): This is really cool to have this chat app</br>visitor_name (visitor_email): no nothing more</br>Chris: Yeah, it's pretty cool :)</br>Chris: OK, take care</br>visitor_name (visitor_email): Thanks again</br>Chris: No problem</br>visitor_name (visitor_email): I am sorry Chris, but I just downloaded current release file from ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/gene_interactions/c_elegans.PRJNA275000.current.gene_interactions.txt.gz, but it is still WS250 as mentioned inside the file on 2nd line. Is it just because of the mistake or it is WS250 ?</br>Chris: Oh, hmmm, let me look into it</br>Chris: I'm not sure of the answer yet, but note that this is for the PRJNA275000 bioproject for C. elegans which is not the canonical version</br>Chris: there is a similar file for the canonical PRJNA13758 above that</br>visitor_name (visitor_email): OK, thanks again for your quick answer.</br>Chris: Actually, they both say WS250</br>Chris: I'm looking into why</br>Chris: Hi visitor_name, let me look into it and email you back a little later, is that OK?</br>visitor_name (visitor_email): No problem at all. Thanks</br>Chris: OK thanks</br>Chris: is there anything else for now?</br>visitor_name (visitor_email): No Chris, that was it</br>Chris: OK, I'll email you in a bit

**Reported by:** Nish**\* (thak******************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-2-">http://www.wormbase.org/#01-23-2-</a>
**Browser:** Chrome 48.0.2564.82

**Comment by khowe** [comment]
It seems that some of the files made by the website staging process have not been made since WS250. 

Perhaps this is a good opportunity to move the making of these files to Hinxton during the build? That will remove the difficulty of which files get created where / by whom (i.e. it will always be Hinxton). 

@tharris: do you have a list of the files (and, ideally, the scripts used to make them)? There is gene_interactions referred to in this ticket, and functional_descriptions in another. Any others?

**Comment by epaule** [comment]
I just got some requests to come up with something like the C.elegans functional descriptions file for B.malayi. So I had a look at the one on the FTP site and it contains a : 
# No currated functional descriptions for b_malayi yet exist in WormBase 
but there technically are a load of brief_description and automated_descriptions in the database.

Maybe we could adapt it to the collected core species and run it as part of the build for each of them?

**Comment by tharris** [comment]
A long time ago, I wrote a harness that let. anybody drop in data dumpers that would automatically be run during the staging process. It has two components, those that are species related (like functional descriptions) and those that are not (laboratories).

The species related dumpers read the contents of the FTP site (this predates the Assemblies.json file) and runs the same dump script for each species. Most try to dump anything but the functional descriptions did not, and as I recall, it's because people complained that the resultant files were empty for most species for most data types.

**Comment by epaule** [comment]
@draciti rolled out the automatic descriptions for the core species, so it might work for them with slight modification (as in: it needs to use the correct tags)

**Comment by tharris** [comment]
This are the included fields:

Concise_description, Provisional_description, Detailed_description, Automated_description.

Brief_description is not included because, at the time, it was identical to Provisional and Detailed.

**Comment by epaule** [comment]
sounds good. Can you enable it for the collected species?

**Comment by tharris** [comment]
done and synced to the FTP site.

**Comment by epaule** [comment]
meh ... didn't work :-(
Do you restrict the query/postprocessing by something C.elegans specific?

**Comment by chris-grove** [comment]
@epaule 
Has the problem really been addressed? I still can't find updated interactions files on the FTP site.

**Comment by chris-grove** [comment]
@epaule 
Nevermind, Kevin just pointed me to the right directory
