### ISSUE TITLE
Duplicate "ghost" genes in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4842]
I couldn't find a relevant open ticket, although this could be related to #1897

There are several genes that have empty duplicate objects, with a gene public name, but no WB Gene ID and no other information. This is most obvious when trying to generate a list of genes. For example, if I try to create a gene list with the gene unc-26 and then click on "Create List", I get directed to a list confirmation page that displays entries that are in need of disambiguation:

![screen shot 2016-05-23 at 10 34 42 am](https://cloud.githubusercontent.com/assets/611382/15474246/06b09f60-20d2-11e6-814e-cbbcaa900f6a.png)

Clearly the first unc-26 is the one we want, the other one being a "ghost" empty version of the gene that should be removed entirely from the database. There are several genes that exist in WormMine like this.

**Comment by chris-grove** [comment]
@nuin 
I think this issue captures at least some of the existing problem (in im-254) with duplicate genes; there's also a reference above to an older issue (#1897) regarding loading in genes from the GFF. The specific problem is different now than in the example I gave at the time: If I enter the gene name "unc-26" it is properly and uniquely recognized, but if I enter the gene ID "WBGene00006763" I get two copies of the gene entry. Same is for other genes for which I enter a WBGene ID.

**Comment by nuin** [comment]
@chris-grove It seems that this has been solved in im-254, can you double check?

![wormmine__list_confirmation](https://cloud.githubusercontent.com/assets/6273/20683646/0349763a-b56a-11e6-9187-83971082a965.png)

**Comment by chris-grove** [comment]
@nuin 
As mentioned in my last comment, the issue still exists in im-254. For example, try creating a gene list using only WBGene IDs, like WBGene00006763; you will see the duplicates showing up in the disambiguation page:
![screen shot 2016-11-28 at 2 47 02 pm](https://cloud.githubusercontent.com/assets/611382/20689306/94aad3ee-b579-11e6-9ff2-c8a759566803.png)

**Comment by nuin** [comment]
OK, I got the same thing as you @chris-grove. Definitely a merge error which left some IDs empty behind.

**Comment by nuin** [comment]
The problem is with identifiers of type `Gene:WBGene00006763`. I am investigating.

**Comment by nuin** [comment]
Running manually the list search

```sql
SELECT a1_.id AS a2_, a1_.primaryIdentifier AS a3_, a1_.secondaryIdentifier AS a4_, a1_.symbol AS a5_ FROM Gene AS a1_ WHERE (LOWER(a1_.primaryIdentifier) IN ('wbgene00006764') OR LOWER(a1_.secondaryIdentifier) IN ('wbgene00006764') OR LOWER(a1_.symbol) IN ('wbgene00006764')) ORDER BY a1_.id LIMIT 10000;
```
 
we get the main source of the error:
```
   a2_    |         a3_         |   a4_   |      a5_
----------+---------------------+---------+----------------
  4176601 | WBGene00006764      | ZK721.2 | unc-27
 13827715 | Gene:WBGene00006764 |         | WBGene00006764
```

A problem of merging, I am checking the code and the source files for a solution.

**Comment by nuin** [comment]
@chris-grove It seems that with the InterMine update, and the non-requirement to use our own GFF3 parser, we skip a piece of code that stripped the `Gene:` from the gene ID in the GFF3. I am working on the GFF3 pre-processing to add this.

**Comment by chris-grove** [comment]
@nuin 
OK, sounds good

**Comment by nuin** [comment]
@chris-grove just finished a test build with our smaller dataset, removing the `Gene:` from GFF3 files, and this was the output for the same query

```sql
SELECT a1_.id AS a2_, a1_.primaryIdentifier AS a3_, a1_.secondaryIdentifier AS a4_, a1_.symbol AS a5_ FROM Gene AS a1_ WHERE (LOWER(a1_.primaryIdentifier) IN ('wbgene00006764') OR LOWER(a1_.secondaryIdentifier) IN ('wbgene00006764') OR LOWER(a1_.symbol) IN ('wbgene00006764')) ORDER BY a1_.id LIMIT 10000;```


```   a2_   |      a3_       | a4_ | a5_ 
---------+----------------+-----+-----
 4175140 | WBGene00006764 |     | 
(1 row)```

**Comment by chris-grove** [comment]
@nuin 
OK, thanks. Just to check, should columns a4_ and a5_ be populated as "ZK721.2" and "unc-27" as above?

**Comment by nuin** [comment]
This is small build, I'm sure I got the previous result on the main build, but I will double check. In the small build we have a handful of genes only.

**Comment by nuin** [comment]
@chris-grove Here is a query with one of the genes in the small dataset

```sql
 SELECT a1_.id AS a2_, a1_.primaryIdentifier AS a3_, a1_.secondaryIdentifier AS a4_, a1_.symbol AS a5_ FROM Gene AS a1_ WHERE (LOWER(a1_.primaryIdentifier) IN ('wbgene00000898') OR LOWER(a1_.secondaryIdentifier) IN ('wbgene00000898') OR LOWER(a1_.symbol) IN ('wbgene00000898')) ORDER BY a1_.id LIMIT 10000;
```


```   
a2_   |      a3_       |   a4_    |  a5_
---------+----------------+----------+-------
 4030526 | WBGene00000898 | Y55D5A.5 | daf-2
```

**Comment by chris-grove** [comment]
@nuin 
OK, got it. Sounds good, thanks!

**Comment by nuin** [comment]
Seems fixed, @chris-grove, let me know what you think

<img width="1826" alt="screen shot 2016-10-07 at 7 25 52 pm" src="https://cloud.githubusercontent.com/assets/6273/20999489/0d309088-bcd2-11e6-8110-19435a9f5c45.png">

**Comment by chris-grove** [comment]
@nuin 
Yes, it looks like the upload problem is fixed. I was trying to perform some queries to make sure the problem was resolved in general, but it seems that queries are not working now (in im-254) but maybe you're working on that now.

I'll close this ticket. Thanks!

**Comment by nuin** [comment]
@chris-grove Yes, templates are not working, I am investigating. Thanks for checking the ticket.
