### ISSUE TITLE
WormMine: im-dev1 testing Feb 6, 2018: Unmerged CDS objects

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6167]
There are 224 CDS objects that have a WormMine ID that is not of the form "CDS:*":

`<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.primaryIdentifier asc">
  <constraint path="CDS.primaryIdentifier" op="NOT LIKE" value="CDS:*"/>
</query>`

If I copy the list of WormMine IDs for these and then try to generate a list of CDS objects in WormMine, each one has a redundant/duplicate/unmerged counterpart that needs to be manually selected on the list disambiguation page. 

![screen shot 2018-02-06 at 3 32 36 pm](https://user-images.githubusercontent.com/611382/35882689-ff3a7a18-0b52-11e8-9c29-03e298f4f75c.png)

I won't list all 224 here, but here's 20 of them (WormMine IDs):

B0207.4
B0336.1a
B0336.1b
B0344.2
B0432.5a
B0432.5b
B0432.5c
B0478.1a
B0478.1b
C01C7.1a
C01C7.1b
C01G6.8a
C01G6.8b
C01G6.8c
C02H7.3a
C02H7.3b
C03C10.1
C03C11.2
C05G5.4
C15B12.6a

If I were to do a query lookup of any of these, I get two results with misaligned identifiers:

`<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.primaryIdentifier asc">
  <constraint path="CDS" op="LOOKUP" value="B0207.4" extraValue=""/>
</query>`

![screen shot 2018-02-06 at 3 31 26 pm](https://user-images.githubusercontent.com/611382/35882648-df4c82e6-0b52-11e8-8c18-745a70b89563.png)

**Comment by nuin** [comment]
This is coming from RNAi and Transcript that need to be pre-processed to get the `CDS:` label in the XML. I am working on checking other possible sources. I don't think we have a pre-processing script for RNAi, so I will work on it.

**Comment by nuin** [comment]
Query above is returning empty at the moment. Also `psql` query looks like

```sql
select * from cds where primaryidentifier = 'C05G5.4';


 secondaryidentifier | symbol | primaryidentifier | lastupdated | length | id | name | scoretype | score | geneid | chromosomeid | chromosomelocationid | organismid |│··········
 sequenceid | proteinid | sequenceontologytermid | class                                                                                                              │··········
---------------------+--------+-------------------+-------------+--------+----+------+-----------+-------+--------+--------------+----------------------+------------+│··········
------------+-----------+------------------------+-------                                                                                                             │··········
(0 rows)
```

Closing.

**Comment by chris-grove** [comment]
The CDS objects that have no "CDS:*" prefix are now gone, which is good, but now there are 114 CDS objects whose WormMine ID is of the form "CDS:CDS:*":

`<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.primaryIdentifier asc">
  <constraint path="CDS.primaryIdentifier" op="LIKE" value="CDS:CDS:*"/>
</query>`

These also represent unmerged CDS objects, as seen by this query:

`<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="CDS.primaryIdentifier" code="A" op="CONTAINS" value="B0207.4"/>
  <constraint path="CDS.symbol" code="B" op="CONTAINS" value="B0207.4"/>
</query>`

![screen shot 2018-02-07 at 9 01 07 am](https://user-images.githubusercontent.com/611382/35920289-7f915848-0be5-11e8-917a-1eaf1beadf03.png)

**Comment by nuin** [comment]
The issue is on the perl script that adds the`CDS:` label to the items in the XML. In some cases depending on how the XML is set it adds a duplicate. I am making some changes to it and I will double check before running a new build.

**Comment by nuin** [comment]
<img width="1652" alt="screen shot 2018-02-07 at 1 54 17 pm" src="https://user-images.githubusercontent.com/6273/35941110-6b808dc8-0c0e-11e8-9aab-2049b4997091.png">

Seems fixed with the recent changes.

**Comment by chris-grove** [comment]
This is still an issue on im-dev1. The last query I mentioned:

`<query name="" model="genomic" view="CDS.primaryIdentifier CDS.symbol" longDescription="" sortOrder="CDS.primaryIdentifier asc" constraintLogic="A or B"> <constraint path="CDS.primaryIdentifier" code="A" op="CONTAINS" value="B0207.4"/> <constraint path="CDS.symbol" code="B" op="CONTAINS" value="B0207.4"/> </query>`

is still showing unmerged CDS objects:

![screen shot 2018-02-07 at 5 10 30 pm](https://user-images.githubusercontent.com/611382/35944295-e6a86af0-0c29-11e8-8527-cafc6c9f1338.png)

Maybe this would be fixed with a full build, but I'd rather not close the issue until I know it's resolved.

**Comment by nuin** [comment]
Coming from protein.xml, fixed and rebuilding.

**Comment by nuin** [comment]
Seems fine now. 
![screen shot 2018-01-31 at 7 17 08 am](https://user-images.githubusercontent.com/6273/35953302-2a52baf0-0c41-11e8-9883-8a1c8493043c.png)

**Comment by chris-grove** [comment]
@nuin Yes, looks good. Thanks!
