### ISSUE TITLE
Chemical structures are not showing

### ISSUE THREAD

**Issue by kyook** [WormBase/website#6506]
This is in reference to an old request and issue: #4636
There should be chemical structures generated on the fly in the overview window.  These are a requested feature for our metabolomics researchers.  

For example, Indene used to have an image  https://wormbase.org/resources/molecule/WBMol:00000005#021534--10 

Would it be possible to have these back?

**Comment by sibyl229** [comment]
Hi @kyook the molecular structure image should be fixed on staging now. It was related to using HTTPS.

**Comment by kyook** [comment]
Thanks @sibyl229! We still have some problem with the white space. Is there anything that can be done to make the display fit better?

**Comment by sibyl229** [comment]
Hi @kyook is this any better? https://staging.wormbase.org/resources/molecule/WBMol:00000005#01--10

**Comment by chris-grove** [comment]
@sibyl229 
I thought I'd chime in here. The display of the molecule structure image looks good if there are no other data displays in the Overview widget for the molecule, but I found some cases where the large version of the image is covered up by other data elements in the widget. For example, on the page for ivermectin:

https://staging.wormbase.org/resources/molecule/WBMol:00002786#018--10

the molecule use information is overlapping the image, making both hard to read:

![screen shot 2018-07-25 at 4 53 41 pm](https://user-images.githubusercontent.com/611382/43227194-fdfdd038-902b-11e8-97b4-b1a3292e62b6.png)

The situation is little worse for cholesterol:

https://staging.wormbase.org/resources/molecule/WBMol:00003979#018--10

![screen shot 2018-07-25 at 4 53 51 pm](https://user-images.githubusercontent.com/611382/43227213-10c927f8-902c-11e8-8f8f-8418598a959e.png)

Molecules palmitoyl-CoA, succinyl-CoA, and isobutyryl-CoA also suffer from table overlap:

https://staging.wormbase.org/resources/molecule/WBMol:00006440#018--10
https://staging.wormbase.org/resources/molecule/WBMol:00006514#018--10
https://staging.wormbase.org/resources/molecule/WBMol:00006318#018--10

![screen shot 2018-07-25 at 4 54 24 pm](https://user-images.githubusercontent.com/611382/43227285-462942b6-902c-11e8-8da4-b0d56e05d81e.png)

![screen shot 2018-07-25 at 4 54 31 pm](https://user-images.githubusercontent.com/611382/43227303-550a4794-902c-11e8-86ef-f5d46b752895.png)

![screen shot 2018-07-25 at 4 55 44 pm](https://user-images.githubusercontent.com/611382/43227320-601fe738-902c-11e8-8c7c-b3fc20fb5807.png)

@kyook I don't know what you think about it, but maybe we could just show the larger image of the structure as a static image and make sure that the frame isn't concealed by any other data elements?
