### ISSUE TITLE
Custom position frequency matrix tool in JBrowse appears to be broken

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7318]
The "Add motif search track" tool has a custom position frequency matrix (PFM) upload option to create custom motif tracks, but as far as I can tell it doesn't work. I put in a track name and all the PFM info and click on "Search" but nothing happens. This is the case on Chrome and Firefox.

**Comment by scottcain** [comment]
Hi @chris-grove ,

It's not so much broken as it is EXTREMELY finicky.  At the moment, you must give it a name, and the matrix must be entered as numbers with a single space between them with no prefix (like "A:", which you might think is required given the "ghost" text that is there).  So, even though it's not technically broken, the fact that only I know how to use it is problematic :-)

Things I'll do to make it more user friendly:

- [ ] Allow more than one space between numbers
- [ ] Add "required" to the track name field
- [ ] Allow a prefix like "A:"
- [ ] Possibly add some help text

**Comment by chris-grove** [comment]
@scottcain 
OK thanks, that all sounds great!

**Comment by chris-grove** [comment]
One more suggestion, actually:
- [ ] Provide indicator that something is or isn't happening when clicking on "Search"

**Comment by scottcain** [comment]
Several of the items in the checklist have been addressed and the result is running on staging. I'll work on adding concise but useful help text.  

Adding a message about "something happening" is not easy: if something has gone wrong, generally the result either should be you see a track that has nothing in it, which implies that it is doing something but perhaps not what you want (and there isn't anything I can really do about that), or something went really wrong, and you'll see "loading" forever in the track (and an error message in the javascript console).  That is also pretty difficult to catch, since something happened that I didn't anticipate and resulted in a "crash".

Actually, in the former case (something happening but not what you expect), I might be able to add an option to the track dropdown menu (where "about this track" lives) that will create a popup window with the matrix that the track is using is regurgitated, which would at least let people check that the matrix they thought they put in is actually what JBrowse is using for computation.  I don't actually know how to do that at the moment, but I imagine I can figure it out.

**Comment by chris-grove** [comment]
OK, thanks @scottcain 
It looks a lot better now. Thanks!

As for the interaction feedback, it would be great if there could be some direct indication that there is something wrong with the input format if that is the case. The changes you made make it more robust, so less likely to result in an error. The thing that bothered me before was that I entered what appeared to be all the correct information, but when I clicked on "Search", nothing happened at all, so there was no way to know that anything was happening, anything was wrong or incorrect, or if I just needed to be patient and wait for the results. I suppose seeing the track with the "Loading" indicator for a long time is a better indication that something is trying to happen but if it's just hanging forever with no indication, that's not ideal. Getting an empty track when there was a submission error is not good either, as it would seem to the user that there are just no hits in that region, not that there was a submission error.

**Comment by scottcain** [comment]
@chris-grove I added brief help text that looks like this.  What do you think? (The part about checking the drop down menu isn't true yet--that's next on the list)

<img width="616" alt="Screen Shot 2019-09-27 at 10 49 05 AM" src="https://user-images.githubusercontent.com/274751/65790507-a415d300-e114-11e9-9365-94c9dd8bb0ac.png">

**Comment by chris-grove** [comment]
@scottcain 
Looks good, thanks!

**Comment by scottcain** [comment]
For error checking--the one thing I can think of the might cause a problem: either the length of the matrix rows aren't equal or not every element is a number (OK, that's two things).  I can check for both of those and pop up an alert box if there is a problem.  I can't think of any other way a user might screw up that would be easy for me to catch.  An example of one of the things in that category would be if the matrix didn't make logical sense, but I wouldn't now how to know that.

I'm working on the drop down menu addition then I'll move on to the error checking.

**Comment by scottcain** [comment]
Two new additions. The first is a stability improvement. I didn't realize that the motif search and regex search tracks were creating IDs that stomped on each other, so if say, a regex track was open and you tried to create a motif track, it would fail silently because it would have the same ID as the already existing regex track.  That is now fixed.

The second is a usability enhancement: the matrix is now placed in the "About" box of the track so that the user can check the matrix that is being used to search, allowing them to verify that the matrix they think they are using really is what they are using. This is true both for custom and built in matrices.  The version of the matrix search with these fixes is currently running on the staging site.

Now moving on to the input error checking described last week.

**Comment by scottcain** [comment]
@chris-grove I think I'm done with this.  Most recent changes were to add pop up alerts if the lines of the matrix are of unequal length and if any of the elements is not a number.  Please take a look at staging and give any feedback if you want or close this issue.

Thanks!

**Comment by chris-grove** [comment]
@scottcain 
OK thanks! Thanks for adding the alerts, but this now has a couple of issues:

1) If there are any non-number characters, when I click on "Search" I get the pop-up alert notifying me of this. While the pop-up is showing, I cannot make any edits to the matrix input to fix it, so I click on "OK" on the pop-up message. This dismisses the pop-up only to produce a second pop-up with the same message, and again I cannot make any edits to fix the input. I click "OK" on the second pop-up and then I get a third pop-up, still can't make edits. I click "OK" on the third pop-up, and I get a fourth pop-up, still no edits can be made. Then, I click "OK" on the fourth pop-up and the whole input box disappears and the custom track is added, apparently with the errors in place with no opportunity to make the fixes to the input. Could we (A) make only a single alert pop-up appear, (B) allow the single pop-up message to disappear when clicking on the "OK" in the message and (C) have the input dialog box remain in place after dismissing the alert pop-up so that the user can then go ahead and make edits to fix their input?

2) The example, shadow/grey text for the matrix still shows:

A:0 12 0 4...
C:12 0 0 6...
G:0 0 12 0...
T:0 0 0 2...

but if I enter that same text I get an error because now I cannot prefix the numerical entries with the base letter and a colon. Could we either (A) allow the base letter prefix with a colon as in the example text or (B) remove the base letter with colon from the example text and instead put base letter labels to the left of each input field?

**Comment by chris-grove** [comment]
Also, the input for the matrix appears to be intolerant to leading or trailing whitespace on any line: if the line starts or ends with a whitespace character I get the pop-up alert notifying me that a non-number entry was made. Can we strip leading and trailing whitespace from entries to prevent this?

**Comment by chris-grove** [comment]
Same comment goes for the alert for entries of differing length: The pop-up alert appears (once), I can click OK to dismiss the pop-up, but then the whole input dialog box also disappears and I can't make edits to my input and then the track appears (apparently with errors; maybe nothing rendered at all?).

**Comment by scottcain** [comment]
Thanks for the great feedback--the leading/trailing white space and labels should be allowed; I'll try some more testing for them.

The alert boxes do need more work and I've got an idea of what I need to do.

**Comment by scottcain** [comment]
@chris-grove 

I fixed those items on staging:
* Leading and trailing white space is now accepted in the matrix lines
* Alert boxes are better:
**You only get one no matter how many NaNs are in the matrix
**The dialog won't dismiss if an alert is triggered

Let me know what you think.

**Comment by chris-grove** [comment]
@scottcain 
OK, much better thanks. I'm still not able to submit entries with any leading or trailing whitespace on Chrome or Firefox

**Comment by scottcain** [comment]
Could that be a caching thing?

**Comment by chris-grove** [comment]
I don't think so. I've cleared my cache on both browsers and I'm still getting errors whenever there is any leading or trailing whitespace

**Comment by scottcain** [comment]
I've tested on both Chrome and Firefox on a Mac and it's working for me.  Here are things I've used in testing:
```
--  A: 4  4  4  1  0  1  0  0  0  22  0  10  8  3  --
-- C:3 3 4 0 0 0 0 1 0 0 21 3 5 10--
--G:9 7 12 1 0 24 0 0 0 2 0 6 3 1--
--T: 7 10 5 23 25 0 25 24 25 1 4 5 7 8 --
```
(The hyphens are not part of the test data; they're to indicate where there are leading and trailing space.)

If you're doing something different, please let me know.  If not, could you try incognito mode and let me know if that makes a difference.

**Comment by chris-grove** [comment]
If I enter *exactly* what you have above, it works, but if I remove the base letter colon prefix on each line I get an error, even if the entries are all numbers and the number of entries are all the same. I thought we wanted to allow users to enter without the base-colon prefix as well.

**Comment by scottcain** [comment]
OK, back to the drawing board :-) Shouldn't be too hard to fix.

**Comment by scottcain** [comment]
@chris-grove 

OK, once again I think I've got it--I was trying to be too clever before, stripping both a preceding label and white space at the same time, which meant that if there wasn't a label, no whitespace got trimmed.

**Comment by chris-grove** [comment]
@scottcain 
OK, looks great! Thanks! Closing.
